language: node_js

node_js:
  - "12"

script:
    - npm test
    - npm run build

env: 
  CI: false


deploy: 
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy Release"
  on:
    branch: main